version: '3.8'

services:
  app:
    build:
      context: "."
      dockerfile: Dockerfile
    container_name: fushimanga-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ../:/var/www
  nginx:
    image: nginx:1.19-alpine
    container_name: fushimanga-nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ../:/var/www
      - ./nginx:/etc/nginx/conf.d
  db:
    container_name: fushimanga-db
    image: mysql:8.0
    volumes:
      - ./storage/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: razik
    ports:
      - "3306:3306"
  cron:
    container_name: fushimanga-cron
    build: ./cron
    volumes:
      - ../:/var/www
      - ./log/cron:/var/log/cron
  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'
    ports:
      - "1025:1025"
      - "8025:8025"